#!/bin/bash
# =============================================
# Rahe Kaba ERP - VPS Migration Script
# Run this AFTER cloning the repo on your VPS
# =============================================

set -e

echo "🚀 Starting Rahe Kaba ERP VPS Migration..."

# 1. Replace Supabase client with custom API client
echo "📝 Swapping Supabase client for custom API..."
cat > src/integrations/supabase/client.ts << 'CLIENTEOF'
// Custom API client - replaces Supabase
// This file was auto-generated by the migration script
export { supabase } from "../../lib/api";
CLIENTEOF

# 2. Add VITE_API_URL to .env
echo "📝 Updating .env..."
cat > .env << 'ENVEOF'
VITE_API_URL=/api
ENVEOF

# 3. Install frontend dependencies and build
echo "📦 Installing frontend dependencies..."
npm install

echo "🔨 Building frontend..."
npm run build

# 4. Setup backend
echo "📦 Setting up backend..."
cd server
npm install
mkdir -p uploads

# 5. Check if .env exists for server
if [ ! -f .env ]; then
  cp .env.example .env
  echo "⚠️  IMPORTANT: Edit server/.env with your database credentials!"
  echo "   nano server/.env"
fi

cd ..

echo ""
echo "✅ Migration complete!"
echo ""
echo "Next steps:"
echo "1. Setup PostgreSQL: sudo -u postgres psql -d rahekaba -f server/schema.sql"
echo "2. Edit server/.env with your database password"
echo "3. Start backend: cd server && node index.js"
echo "4. Update Nginx config (see server/DEPLOY.md)"
echo ""
echo "Default admin login:"
echo "  Email: admin@rahekaba.com"
echo "  Password: Admin@123456"
